### ISSUE TITLE
Build fails with libgit-1.0.0

### ISSUE THREAD

**Issue by ptesarik** [joergroedel/git-fixes#3]
See https://build.opensuse.org/package/show/Kernel:tools/git-fixes for `openSUSE_Factory`:

```
[   54s] g++ -O3 -Wall -std=c++11 -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -g   -c -o who.o who.cc
[   56s] git-fixes.cc: In function 'std::string config_get_string_nofail(git_config*, const char*)':
[   56s] git-fixes.cc:928:44: error: invalid conversion from 'const git_config_entry**' to 'git_config_entry**' [-fpermissive]
[   56s]   if (git_config_get_entry(&entry, cfg, name))
[   56s]                                             ^
```

**Comment by joergroedel** [comment]
Thanks for the report, working on a fix.

**Comment by joergroedel** [comment]
Fix is pushed. Also updated the static build to use libgit2-1.0.0, works on openSUSE Tumbleweed and Leap 15.1.
